"use client";
import { useState } from "react";
import type { LectureAnalysis } from "./analysisTypes";
import { timestamp } from "./analysisTypes";
import "./real-results.css";

export default function RealStudyResults({ analysis, duration, download }: { analysis: LectureAnalysis; duration: number; download: () => void }) {
 const [view,setView]=useState<"summary"|"transcript"|"study">("summary"),guide=analysis.guide;
 return <div className="real-results"><section className="result-heading"><div><span>✦ REAL LECTURE ANALYSIS</span><h1>{guide.title || "Analyzed lecture"}</h1><p>{guide.className || "Unsorted class"} · {timestamp(duration)} · Grounded in {analysis.transcript.lines.length || 1} source segment(s)</p></div><div className="result-confidence"><b>{guide.confidence}%</b><small>AI confidence</small></div></section><nav><button className={view==="summary"?"active":""} onClick={()=>setView("summary")}>Summary</button><button className={view==="transcript"?"active":""} onClick={()=>setView("transcript")}>Transcript</button><button className={view==="study"?"active":""} onClick={()=>setView("study")}>Study tools</button><button onClick={download}>⇩ Recording</button></nav>{view==="summary"&&<div className="result-grid"><article><span>FINAL AI SUMMARY</span><h2>What the lecture covered</h2><p>{guide.summary}</p><h3>Key takeaways</h3><ul>{guide.keyTakeaways.map(item=><li key={item}>{item}</li>)}</ul></article><aside><span>HOMEWORK &amp; ACTIONS</span><h2>{guide.homework.length?`${guide.homework.length} detected item${guide.homework.length===1?"":"s"}`:"No homework detected"}</h2>{guide.homework.map(item=><div className="real-homework" key={item.task}><b>{item.task}</b><small>{item.deadline||"No deadline stated"}</small><em>Evidence: “{item.evidence}”</em></div>)}{!guide.homework.length&&<p>The transcript did not explicitly state an assignment. Anchor did not invent one.</p>}<h3>Accuracy limits</h3>{guide.limitations.map(item=><p className="limit" key={item}>ⓘ {item}</p>)}</aside></div>}{view==="transcript"&&<section className="real-transcript">{analysis.transcript.lines.length?analysis.transcript.lines.map((line,index)=><article key={`${line.start}-${index}`}><time>{timestamp(line.start)}</time><div><b>{line.speaker}</b><p>{line.text}</p></div></article>):<p>{analysis.transcript.text}</p>}</section>}{view==="study"&&<div className="study-results"><section><span>KEY CONCEPTS</span>{guide.concepts.map(item=><article key={item.name}><h3>{item.name}</h3><p>{item.explanation}</p><small>Evidence: “{item.evidence}”</small></article>)}</section><section><span>VOCABULARY</span>{guide.vocabulary.map(item=><article key={item.term}><h3>{item.term}</h3><p>{item.definition}</p></article>)}</section><section><span>FLASHCARDS</span>{guide.flashcards.map(item=><article key={item.front}><h3>{item.front}</h3><p>{item.back}</p></article>)}</section><section><span>REVIEW QUESTIONS</span>{guide.quiz.map(item=><article key={item.question}><h3>{item.question}</h3><p>{item.answer}</p><small>{item.explanation}</small></article>)}</section></div>}<footer>Transcribed with {analysis.models.transcription} · Analyzed with {analysis.models.analysis} · Verify important details against the recording</footer></div>
}
