//
//  SessionStore.swift
//  Anchor (Echor)
//
//  Persists recorded class sessions (transcript + AI recap) as JSON in the
//  app's Documents directory. Everything stays on-device.
//

import Combine
import Foundation
import SwiftUI

/// Otter-style AI notes for a session, generated by the local Ollama model.
struct SessionInsights: Codable, Equatable {
    var overview: String
    var keyPoints: [String]
    var actionItems: [String]
}

struct RecordingSession: Identifiable, Codable, Equatable {
    let id: UUID
    var title: String
    var subject: String
    var date: Date
    var duration: TimeInterval
    var transcript: String
    /// Legacy plain-text recap from older saves; new sessions use `insights`.
    var recap: String?
    var insights: SessionInsights?
}

@MainActor
final class SessionStore: ObservableObject {
    @Published private(set) var sessions: [RecordingSession] = [] {
        didSet { save() }
    }

    private let fileURL: URL

    init() {
        let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        fileURL = documents.appendingPathComponent("sessions.json")
        load()
    }

    // MARK: - Mutations

    func add(_ session: RecordingSession) {
        sessions.insert(session, at: 0)
    }

    func updateInsights(id: UUID, insights: SessionInsights) {
        guard let index = sessions.firstIndex(where: { $0.id == id }) else { return }
        sessions[index].insights = insights
    }

    func delete(_ session: RecordingSession) {
        sessions.removeAll { $0.id == session.id }
    }

    // MARK: - Dashboard stats

    var totalDuration: TimeInterval {
        sessions.reduce(0) { $0 + $1.duration }
    }

    /// Distinct subjects, most recently used first.
    var subjects: [String] {
        var seen = Set<String>()
        return sessions.compactMap { seen.insert($0.subject).inserted ? $0.subject : nil }
    }

    func sessions(for subject: String) -> [RecordingSession] {
        sessions.filter { $0.subject == subject }
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: fileURL),
              let decoded = try? JSONDecoder().decode([RecordingSession].self, from: data) else { return }
        sessions = decoded
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(sessions) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }
}

/// Stable color per subject so tags look consistent across launches.
func subjectColor(for subject: String) -> Color {
    let palette: [Color] = [.blue, .purple, .pink, .orange, .teal, .green, .indigo, .red]
    let hash = subject.unicodeScalars.reduce(0) { ($0 &* 31 &+ Int($1.value)) }
    return palette[abs(hash) % palette.count]
}
